# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://estatup.github.io/
baseurl: /sustain/
title: Eduardo Vargas Ferreira
author: Eduardo Vargas Ferreira
description: Personal blog and resume
avatar: profile1.png
email: e.ferreira@ufpr.br
    
# needed for travis-ci build
exclude: [vendor]
