# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://estatup.github.io/
baseurl: /sustain/
title: Eduardo Vargas Ferreira
author: Eduardo Vargas Ferreira
description: Personal blog and resume
avatar: profile1.png
email: e.ferreira@ufpr.br
github: estatup/sustain # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1

<div class="social">
          <a target="_blank" style="opacity: 1;" href="mailto:walmes@ufpr.br"><i class="fa fa-2x fa-envelope"></i></a>
          <a target="_blank" style="opacity: 1;" href="http://lattes.cnpq.br/4410617539281650"><i class="ai ai-2x ai-lattes"></i></a>
          <a target="_blank" style="opacity: 1;" href="https://scholar.google.com.br/citations?user=pb-91n8AAAAJ"><i class="ai ai-2x ai-google-scholar"></i></a>
          <a target="_blank" style="opacity: 1;" href="https://www.researchgate.net/profile/Walmes_Zeviani2"><i class="ai ai-2x ai-researchgate"></i></a>
          <a target="_blank" style="opacity: 1;" href="https://orcid.org/0000-0001-5503-8565"><i class="ai ai-2x ai-orcid"></i></a>
          <a target="_blank" style="opacity: 1;" href="https://www.mendeley.com/profiles/walmes-zeviani1/"><i class="ai ai-2x ai-mendeley"></i></a>
          <a target="_blank" style="opacity: 1;" href="https://github.com/walmes"><i class="fa fa-2x fa-github"></i></a>
          <a target="_blank" style="opacity: 1;" href="https://gitlab.c3sl.ufpr.br/walmes"><i class="fa fa-2x fa-gitlab"></i></a>
          <a target="_blank" style="opacity: 1;" href="https://www.linkedin.com/in/walmes-marques-zeviani-41b8b650/"><i class="fa fa-2x fa-linkedin"></i></a>
          <a target="_blank" style="opacity: 1;" href="https://twitter.com/walmeszeviani"><i class="fa fa-2x fa-twitter"></i></a>
          <!-- <a target="_blank" style="opacity: 1;" href="TODO"><i class="ai ai-2x ai-orcid"></i></a> -->

        </div>
        
# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog
    
# needed for travis-ci build
exclude: [vendor]
